name: 'ticket_classifier'
version: '1.0.0'
config-version: 2

profile: 'ticket_classifier'

model-paths: ['models', 'sources']
seed-paths: ['seeds']
test-paths: ['tests']
analysis-paths: ['analysis']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  ticket_classifier:
    staging:
      +materialized: table
    marts:
      +materialized: table
